### ISSUE TITLE
OKTA-SDK-Dotnet null reference exception

### ISSUE THREAD

**Issue by mmusaev** [okta/okta-sdk-dotnet#646] opened 2023-05-17 23:36 UTC
### Describe the bug?

I followed this example to create an instance of GroupAPI:

var privateKey = new JsonWebKeyConfiguration
{
P = “{{P}}”,
Kty = “RSA”,
Q = “{{Q}}”,
D = “{{D}}”,
E = “{{E}}”,
Kid = “{{P}}”,
Qi = “{{Qi}}”
};

var configuration = new Configuration
{
OktaDomain = “https://{{yourOktaDomain}}”,
AuthorizationMode = AuthorizationMode.PrivateKey,
ClientId = “{{clientId}}”,
Scopes = new List { “okta.users.read”, “okta.apps.read”, “okta.groups.manage”, “okta.groups.manage” }, // Add all the scopes you need
PrivateKey = privateKey
};

services.AddScoped(_ => new GroupApi(configuration ));

However, I get null reference exception when creating GroupApi passing the configuration object.  After ton of raised exceptions, the code eventually succeeds. I am able to connect to my okta tenant and get the response data from okta api calls.

Thank you,
Marat

### What is expected to happen?

There should not be any exceptions raised

### What is the actual behavior?

I don't expect so many exceptions raised.

### Reproduction Steps?

 To reproduce the problem, select the checkbox in the Exceptions Settings window within Visual Studio 2022.  I am using the latest okta-sdk-dotnet version.

### Additional Information?

The code is used within NET 6 api project in Program.cs class.

### .NET Version

The code is used within NET 6 api project in Program.cs class.

### SDK Version

Happens both in OKTA.SDK 6.0.7 and 6.0.10.

### OS version

Windows 10

**Comment by laura-rodriguez** [comment] 2023-05-18 13:16
Hi @mmusaev ,
Thanks for reporting this issue. I'll file an internal ticket for our team.

Internal Ref: OKTA-611865

**Comment by andrewqsmith** [comment] 2023-07-18 19:50
This is a great find @mmusaev and something I hope gets updated soon for the dotnet SDK.

**Comment by chai-deshpande** [comment] 2023-07-21 07:48
The NullReferenceException is thrown while creating an instance of any API client. In my case its the UserApi. On digging further, its because of the call to
[configuration = Sdk.Client.Configuration.GetConfigurationOrDefault(configuration);](https://github.com/okta/okta-sdk-dotnet/blob/f0317653f77e15e0b12d068888429d9346ab8001/src/Okta.Sdk/Api/UserApi.cs#L1006)

this in turn calls
[configBuilder.Build().GetSection("okta").GetSection("client").Bind(compiledConfig);](https://github.com/okta/okta-sdk-dotnet/blob/f0317653f77e15e0b12d068888429d9346ab8001/src/Okta.Sdk/Client/Configuration.cs#L856)

and since there is no okta:client or okta:testing section in the config, the null reference exception is thrown on the Bind method.

**Comment by mmoreno79** [comment] 2024-03-28 15:22
I agree wholly with everyone's assessment here. Until a fix is in place, a quick dirty workaround is to use the overload accepting the IAsynchronousClient parameter. Keyword here is dirty but it accomplishes the same as the first constructor, just without configuration validation. I see there's a PR in place that fixes this issue but hasn't had any movement in months.

Workaround:

```
        var asyncClient = new ApiClient(config.OktaDomain);
        var userApi = new UserApi(asyncClient, config);
```

**Comment by bryanapellanes-okta** [comment] 2024-05-23 13:19
@mmusaev I apologize for the delay in review and resolution of this issue.  Using the reproduction code provided I am not able to reproduce the issue locally on a machine that lacks Okta configuration of any kind.  Is this still an issue? Is there perhaps a specific kind of project that causes the exception?  If you are able to provide a reference project that reproduces the issue that would be greatly helpful.  cc @mmoreno79.  Thank you for your engagement and thanks for using Okta!

**Comment by bryanapellanes-okta** [comment] 2024-06-12 16:30
closing due to inactivity.

**Closed by bryanapellanes-okta** 2024-06-12 16:30 UTC
Labels: bug

**Comment by gao-artur** [comment] 2024-10-29 09:46
@bryanapellanes-okta I spent 2 hours fighting this NRE. The simplest way to reproduce it is creating a json config with private key
```json
{
  "Okta": {
    "Client": {
      "OktaDomain": "https://xxx.com",
      "ClientId": "xxx",
      "AuthorizationMode": "PrivateKey",
      "PrivateKey": {
        "p": "xxx",
        "kty": "RSA",
        "q": "xxx",
        "d": "xxx",
        "e": "xxx",
        "use": "sig",
        "qi": "xxx",
        "dp": "xxx",
        "alg": "RS256",
        "dq": "xxx",
        "n": "xxx"
      },
      "Scopes": [
        "okta.users.manage"
      ]
    }
  }
}
```

Then do this
```c#
var config1 = Okta.Sdk.Client.Configuration.GetConfigurationOrDefault();
var config2 = Okta.Sdk.Client.Configuration.GetConfigurationOrDefault(config1);
```

The exception is thrown on the second call to `GetConfigurationOrDefault`.
What's the catch? This is a handled exception 🤦‍♂️
I got this exception because I have Source Link enabled and `Common Language Runtime Exceptions` selected.
Just unselect the CLR exceptions and continue running the code.

**Comment by dbloch3643** [comment] 2025-03-13 20:47
> closing due to inactivity.

This should not be closed, this is still happening in Okta.SDK 9.x
