### ISSUE TITLE
OktaClient Does Not Send Authorization Header After Authentication

### ISSUE THREAD

**Issue by wcarson** [okta/okta-sdk-dotnet#40] opened 2017-05-25 15:10 UTC
If an OktaClient is used to submit an Authentication request (which does not require an API key), any subsequent calls from the same client will not have an authorization header.

Steps to reproduce:

1. Create `OktaClient `object
2. Use the client to call a method that requires an API key (e.g. `UsersClient.Get()`) - this will work
3. Use the client to call a method that does not require an API key (e.g. `AuthClient.Authenticate()`) - this will work
4. Use the client to repeat the same method as in step 2 above - this will fail with "`E0000005 - Invalid Session`" error because the Authorization header is missing

Tracing through the code, this appears to be caused when during the Authenticate() call, the code [calls the underlying Post method with a bAddAuthorizationHeader value of false](https://github.com/okta/oktasdk-csharp/blob/master/Okta.Core/Clients/AuthClient.cs#L41), which instructs code in the underlying OktaHttpClient to [remove the Authorization header from the DefaultRequestHeaders collection](https://github.com/okta/oktasdk-csharp/blob/master/Okta.Core/OktaHttpClient.cs#L176), which effectively removes it from all subsequent calls from this client. The only way to get the Authorization header back, is to set the ApiToken property again on the OktaHttpClient, but even this approach can cause issues when more than one thread is accessing the client.

The solution is to add the Authorization header on a per-request as-needed basis instead of a per-client default (DefaultRequestHeaders) as it is implemented now.

Update: Looks like this may also be the root cause for #33.

**Comment by nbarbettini** [comment] 2017-05-25 16:03
Thanks for reporting this @wcarson. I agree, I believe the root cause is setting the DefaultRequestHeaders, which should not happen.

FYI, we are currently developing a new major version of this library, which should fix this and other bugs. I'll leave this issue open until we have more updates.

**Comment by nbarbettini** [comment] 2018-06-08 18:56
We are close to releasing the stable version of the .NET SDK 1.0, a major rewrite that fixes this and a number of other bugs. 

While annoying, it's possible to work around this bug by **always** creating a new `OktaClient` each time you need to call Okta. In other words, don't treat this SDK as a singleton in versions below 1.0. Instantiating an `OktaClient` (or sub-clients) is a fairly cheap operation so this shouldn't cause major perf issues.

I'm going to close this issue as "won't fix" because there is a workaround available for v0.3.3 and we'll encourage everyone to upgrade to 1.0+ if possible.

(And thanks again for your help @wcarson! Sorry for the long delay on this issue.)

**Closed by nbarbettini** 2018-06-08 18:56 UTC
Labels: legacy
