### ISSUE TITLE
IDX11025: Cannot serialize object of type: 'System.Guid' into property: 'jti'.

### ISSUE THREAD

**Issue by pedrollanesbenchmark** [okta/okta-sdk-dotnet#737] opened 2024-08-08 08:43 UTC
### Describe the bug?

Excecption detail:
   at Okta.Sdk.Client.DefaultDpopProofJwtGenerator.GenerateJwt(String nonce, String httpMethod, String uri, String accessToken)
   at Okta.Sdk.Api.OAuthApi.<GetBearerTokenWithHttpInfoAsync>d__18.MoveNext()
   at Okta.Sdk.Api.OAuthApi.<GetBearerTokenAsync>d__17.MoveNext()
   at Okta.Sdk.Client.DefaultOAuthTokenProvider.<RequestAccessTokenAsync>d__15.MoveNext()
   at Okta.Sdk.Client.DefaultOAuthTokenProvider.<GetAccessTokenResponseAsync>d__7.MoveNext()
   at Okta.Sdk.Client.DefaultOAuthTokenProvider.<AddOrUpdateAuthorizationHeader>d__12.MoveNext()
   at Okta.Sdk.Api.UserApi.<GetUserWithHttpInfoAsync>d__43.MoveNext()
   at Okta.Sdk.Api.UserApi.<GetUserAsync>d__42.MoveNext()

### What is expected to happen?

it seems that DefaultDpopProofJwtGenerator need to make tostring when it set jti guid.

### What is the actual behavior?

It crash

### Reproduction Steps?

calling to UserApi

### Additional Information?

JTI microsoft is string:
https://learn.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtpayload.jti?view=msal-web-dotnet-latest#system-identitymodel-tokens-jwt-jwtpayload-jti

### .NET Version

netcore8

### SDK Version

8.0.1

### OS version

BuildNumber  Caption                          OSArchitecture  Version
19045        Microsoft Windows 10 Enterprise  64-bit          10.0.19045

**Comment by bryanapellanes-okta** [comment] 2024-08-08 14:14
This appears to be a duplicate of #682

**Comment by pedrollanesbenchmark** [comment] 2024-08-08 14:37
For more info:
 
The Okta SDK use Microsoft Identity Model >= v6.35.0. If I then upgrade the version of that package to v7.1.2 I get the same error.

**Comment by pedrollanesbenchmark** [comment] 2024-08-09 08:30
> @pedrollanesbenchmark Thanks for bringing this to our attention! I've opened an internal issue for tracking and prioritization [OKTA-791311](https://oktainc.atlassian.net/browse/OKTA-791311). We will work with Developer Support to address your support case and resolve this issue.

Good morning any news?

**Comment by bhavik-thakkar-okta** [comment] 2024-08-27 16:09
Hey @pedrollanesbenchmark thanks for your follow-up. We have currently added this on to our priority list and we will prioritize this accordingly and we will get back to you once its added to our sprint scope for some concrete timelines.

**Closed** 2024-08-27 19:30 UTC
Labels: bug
