### ISSUE TITLE
Using oktaClient.GetAuthClient() function results in invalid session when getting groups for authenticated user

### ISSUE THREAD

**Issue by sohaibajmal-okta** [okta/okta-sdk-dotnet#33] opened 2017-03-31 00:22 UTC
Using oktaClient.GetAuthClient() function to get user followed by getting assigned groups for that user result in invalid session error.

**Comment by sohaibajmal-okta** [comment] 2017-03-31 00:35
Code that gives error.

var oktaClient = new OktaClient(prodkey, new Uri(prodURL));

var authClient = oktaClient.GetAuthClient();

AuthResponse authResponse = authClient.Authenticate("username@domain.com", "Password");

UserGroupsClient userGroups = oktaClient.GetUserGroupsClient(authResponse.Embedded.User);


PagedResults<Okta.Core.Models.Group> groups1 = userGroups.GetList(null, 200, null, Okta.Core.SearchType.Filter, null, null, null);


Code that works.

var oktaClient = new OktaClient(prodkey, new Uri(prodURL));

var settings = new OktaSettings();
settings.ApiToken = "<apikey>";
settings.BaseUri = new Uri("https://org-domain.okta.com");

var authClient = new AuthClient(oktaSettings);

AuthResponse authResponse = authClient.Authenticate("username@domain.com", "Password");

UserGroupsClient userGroups = oktaClient.GetUserGroupsClient(authResponse.Embedded.User);


PagedResults<Okta.Core.Models.Group> groups1 = userGroups.GetList(null, 200, null, Okta.Core.SearchType.Filter, null, null, null);

Reason of error is line "var authClient = oktaClient.GetAuthClient()" that causes error.

GetAuthClient() also initializes object of type AuthClient in OktaClient class (OktaClient.cs)

However, it seems like GetAuthClient calls following constructor of AuthClient class

public AuthClient(IOktaHttpClient clientWrapper) : base(clientWrapper) { resourcePath = Constants.EndpointV1 + Constants.AuthnEndpoint; }

Whereas var authClient = new AuthClient(oktaSettings) calls following constructor

public AuthClient(OktaSettings oktaSettings) : base(oktaSettings) { resourcePath = Constants.EndpointV1 + Constants.AuthnEndpoint; } 

The issue causes the authorization header with api token be skipped from API call. 

Fiddler trace screenshots attached for two API calls, when auth header is included and second when it is not. 
![screen shot 2017-03-30 at 5 34 25 pm](https://cloud.githubusercontent.com/assets/25207880/24531631/3d692f58-156f-11e7-999d-5dc0de2bb7ab.png)
![screen shot 2017-03-30 at 5 34 33 pm](https://cloud.githubusercontent.com/assets/25207880/24531632/3d7be058-156f-11e7-8737-3dbd6b30860a.png)

**Comment by nbarbettini** [comment] 2018-06-08 18:33
Duplicate of #40.

**Closed by nbarbettini** 2018-06-08 18:33 UTC
Labels: duplicate, legacy
