### ISSUE TITLE
Issue saving custom app user attribute for the first time if app is assigned via group membership.

### ISSUE THREAD

**Issue by kvbutler** [okta/okta-sdk-dotnet#490] opened 2021-06-16 13:14 UTC
Hi team see commented code that is broken and API direct call that is working fine.

```csharp
IGroup group = await GetGroupAsync(client);
IApplication app = await group.ListApplications().FirstOrDefaultAsync();

// IAppUser appUser = await app.GetApplicationUserAsync(user.Id);
//appUser.Profile.SetProperty("app_id", userFile.AppId);
//await client.Applications.UpdateApplicationUserAsync(appUser, app.Id, user.Id);

// Hit API directly C# SDK has a bug when app user property is set for the first time (E0000001 appUserMediated, Attribute xxx is a group app attribute).
await client.PostAsync(new HttpRequest
{
    Uri = "/api/v1/apps/{appId}/users/{userId}",
    PathParameters = new Dictionary<string, object>()
    {
        ["appId"] = app.Id,
        ["userId"] = user.Id,
    },
    Payload = new
    {
        profile = new {
            app_id = userFile.AppId
        }
    }
});
```

**Comment by laura-rodriguez** [comment] 2021-06-16 13:40
Hi @kvbutler,

Thank you for reporting this! 

Can I ask you what exception you got when using the `UpdateApplicationUserAsync` method?

**Comment by laura-rodriguez** [comment] 2021-06-16 14:28
Thank @kvbutler! I forgot to ask you what SDK version you're using, can you pls let me know when you have a chance?

**Comment by kvbutler** [comment] 2021-06-16 14:31
Oh yeah good point, I'm a little behind the latest, 3.1.1

**Comment by laura-rodriguez** [comment] 2021-06-16 15:48
Would you mind if I ask what's preventing you to upgrade to the latest?

**Comment by kvbutler** [comment] 2021-06-16 15:51
At this point nothing just need to get time in my sprint, I will try an upgrade and let you know if the issue still persists. Are there many breaking changes between v3 and v5?

**Comment by laura-rodriguez** [comment] 2021-06-16 15:55
Makes sense! There are a few, but I think the most important one is [this in v5](https://github.com/okta/okta-sdk-dotnet/blob/master/CHANGELOG.md#breaking-changes). 

Thanks for all the info you provided 😄  !

**Comment by andriizhegurov-okta** [comment] 2021-11-05 13:00
Hi @kvbutler. Did you try to upgrade to a newer version of the SDK? Can you still see this issue?

**Comment by andriizhegurov-okta** [comment] 2021-11-08 11:43
Hi @kvbutler, I think I know what's the cause of the issue you've seen. 
If you want a new custom attribute to be editable for every AppUser, make sure you select "Scope [ ] User personal" check box when adding the new attribute.
If the check box is not selected, the attribute will be changed on a group level only.

![image](https://user-images.githubusercontent.com/68990515/140735938-4b6379ce-28b1-4e30-aa69-ea1ad9614021.png)

Closing the issue now.

**Closed by andriizhegurov-okta** 2021-11-08 11:43 UTC
Labels: OKTA-404878
